package com.zilker.taxi.constant;

public class Query {
	
	public static final String CHECK_MAIL_EXISTS = "SELECT * FROM CUSTOMER_DETAIL WHERE MAIL=?";
	
	public static final String CHECK_BOOKING_EXISTS = "SELECT * FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";
	
	public static final String CHECK_DRIVER_EXISTS = "SELECT * FROM DRIVER_DETAIL";
	
	public static final String CHECK_CAB_EXISTS = "SELECT * FROM CAB_DETAIL";

	public static final String GET_ROUTES_LIST = "SELECT * from ROUTE_DETAIL";
	
	public static final String INSERT_PERSONAL_DETAILS = "INSERT INTO CUSTOMER_DETAIL(FIRST_NAME, LAST_NAME, MAIL) VALUES(?,?,?)";

	public static final String INSERT_RIDE_DETAILS = "INSERT INTO CAB_RIDE_DETAIL(CUSTOMER_ID, DRIVER_ID, START_TIME, END_TIME, SOURCE_ADDRESS_ID, DESTINATION_ADDRESS_ID, CAB_ID, PRICE) VALUES(?,?,?,?,?,?,?,?)";

	public static final String GET_BOOKING_ID = "SELECT * from CAB_RIDE_DETAIL WHERE CUSTOMER_ID=? AND DRIVER_ID=?";

	public static final String UPDATE_DRIVER_STATUS = "UPDATE DRIVER_DETAIL SET DRIVER_STATUS=? WHERE DRIVER_ID=?";

	public static final String UPDATE_CAB_STATUS = "UPDATE CAB_DETAIL SET CAB_STATUS=? WHERE CAB_ID=?";
	
	public static final String GET_LOCATION_ID = "SELECT * FROM ADDRESS_DETAIL WHERE CITY=?";
	
	public static final String GET_LOCATION = "SELECT * FROM ADDRESS_DETAIL WHERE ADDRESS_ID=?";

	public static final String GET_START_TIME = "SELECT * FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";

	public static final String DISPLAY_PROFILE = "SELECT * FROM CUSTOMER_DETAIL WHERE mail=?";

	public static final String DISPLAY_BOOKING_DETAILS = "SELECT * FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";

	public static final String DELETE_RIDE = "DELETE FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";
	
	public static final String UPDATE_PROFILE = "UPDATE CUSTOMER_DETAIL SET FIRST_NAME=?, LAST_NAME=? WHERE MAIL=?";

	public static final String UPDATE_RIDE_DETAILS = "UPDATE CAB_RIDE_DETAIL SET START_TIME=?, END_TIME=?, SOURCE_ADDRESS_ID=?, DESTINATION_ADDRESS_ID=?, PRICE=? WHERE CAB_RIDE_ID=?";

	public static final String DELETE_PROFILE = "DELETE FROM CUSTOMER_DETAIL WHERE CUSTOMER_ID=?";
	
	public static final String DELETE_CUSTOMER_RIDES = "DELETE FROM CAB_RIDE_DETAIL WHERE CUSTOMER_ID=?";
	
}
