package com.zilker.taxi.constant;

public class SQLConstants {
		
	public static final String CHECK_CONTACT_EXISTS = "SELECT USER_ID FROM USER_DETAIL WHERE CONTACT=?";
	
	public static final String GET_USER_ID = "SELECT USER_ID FROM USER_DETAIL WHERE CONTACT=?";
	
	public static final String INSERT_PERSONAL_DETAILS = "INSERT INTO USER_DETAIL(USERNAME, MAIL, CONTACT, ROLE, PASS) VALUES(?,?,?,?,?)";

	public static final String UPDATE_USER_ID = "UPDATE USER_DETAIL SET CREATED_BY=?, UPDATED_BY=?, UPDATED_AT=current_timestamp WHERE CONTACT=?";

	public static final String INSERT_USER_ADDRESS = "INSERT INTO ADDRESS_DETAIL(USER_ID, STREET_ADDRESS, CITY, ZIP_CODE, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?,?)";

	public static final String CHECK_LOGIN = "SELECT ROLE FROM USER_DETAIL WHERE CONTACT=? AND PASS=?";

	public static final String DISPLAY_LOCATIONS = "SELECT STREET_ADDRESS, ZIP_CODE FROM ADDRESS_DETAIL";

	public static final String INSERT_LICENCE_DETAILS = "INSERT INTO DRIVER_DETAIL(USER_ID, LICENCE_NUMBER, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?)";

	public static final String GET_CAB_ID = "SELECT CAB_ID FROM CAB_DETAIL WHERE CAB_STATUS=?";
	
	public static final String INSERT_CAB_DRIVER = "INSERT INTO CAB_DRIVER(DRIVER_ID, CAB_ID, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?)";
	
	public static final String UPDATE_CAB_STATUS = "UPDATE CAB_DETAIL SET CAB_STATUS=? WHERE CAB_ID=?";
	
	public static final String INSERT_CAB_MODEL_DETAILS = "INSERT INTO CAB_MODEL(MODEL_NAME, MODEL_DESCRIPTION, NUMBER_OF_SEATS, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?)";

	public static final String INSERT_CAB_LAUNCH_DETAILS = "INSERT INTO CAB_DETAIL(LICENCE_PLATE, LATITUDE, LONGITUDE, MODEL_ID, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?,?)";

	public static final String DISPLAY_CAB_MODELS = "SELECT MODEL_ID, MODEL_NAME, MODEL_DESCRIPTION, NUMBER_OF_SEATS FROM CAB_MODEL";

	public static final String GET_MODEL_ID = "SELECT MODEL_ID FROM CAB_MODEL WHERE CAB_ID=?";

	public static final String GET_MODEL_CAB_ID = "SELECT CAB_ID FROM CAB_DETAIL WHERE MODEL_ID=? AND CAB_STATUS=?";

	public static final String GET_CAB_LOCATIONS = "SELECT CAB_ID, LATITUDE, LONGITUDE FROM CAB_DETAIL WHERE CAB_STATUS=unavailable";

	public static final String GET_DRIVER_ID = "SELECT DRIVER_ID FROM CAB_DRIVER WHERE CAB_ID=?";

	public static final String GET_CAB_SEATS = "SELECT NUMBER_OF_SEATS FROM CAB_MODEL WHERE MODEL_ID=?";

	
	
	
	
	public static final String CHECK_BOOKING_EXISTS = "SELECT CAB_RIDE_ID FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";
	
	public static final String CHECK_DRIVER_EXISTS = "SELECT DRIVER_ID, DRIVER_STATUS FROM DRIVER_DETAIL";
	
	public static final String CHECK_CAB_EXISTS = "SELECT CAB_ID, CAB_STATUS FROM CAB_DETAIL";

	public static final String GET_ROUTES_LIST = "SELECT * FROM ROUTE_DETAIL";
	
	public static final String INSERT_RIDE_DETAILS = "INSERT INTO CAB_RIDE_DETAIL(CUSTOMER_ID, DRIVER_ID, START_TIME, END_TIME, SOURCE_ADDRESS_ID, DESTINATION_ADDRESS_ID, CAB_ID, PRICE) VALUES(?,?,?,?,?,?,?,?)";

	public static final String GET_BOOKING_ID = "SELECT CAB_RIDE_ID FROM CAB_RIDE_DETAIL WHERE CUSTOMER_ID=? AND DRIVER_ID=?";

	public static final String UPDATE_DRIVER_STATUS = "UPDATE DRIVER_DETAIL SET DRIVER_STATUS=? WHERE DRIVER_ID=?";
		
	public static final String GET_LOCATION = "SELECT CITY FROM ADDRESS_DETAIL WHERE ADDRESS_ID=?";

	public static final String GET_START_TIME = "SELECT START_TIME FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";

	public static final String DISPLAY_PROFILE = "SELECT * FROM CUSTOMER_DETAIL WHERE mail=?";

	public static final String DISPLAY_BOOKING_DETAILS = "SELECT * FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";

	public static final String DELETE_RIDE = "DELETE FROM CAB_RIDE_DETAIL WHERE CAB_RIDE_ID=?";
	
	public static final String UPDATE_PROFILE = "UPDATE CUSTOMER_DETAIL SET FIRST_NAME=?, LAST_NAME=? WHERE MAIL=?";

	public static final String UPDATE_RIDE_DETAILS = "UPDATE CAB_RIDE_DETAIL SET START_TIME=?, END_TIME=?, SOURCE_ADDRESS_ID=?, DESTINATION_ADDRESS_ID=?, PRICE=? WHERE CAB_RIDE_ID=?";

	public static final String DELETE_PROFILE = "DELETE FROM CUSTOMER_DETAIL WHERE CUSTOMER_ID=?";
	
	public static final String DELETE_CUSTOMER_RIDES = "DELETE FROM CAB_RIDE_DETAIL WHERE CUSTOMER_ID=?";
	
}
