package com.zilker.taxi.constant;

public class SQLConstants {
	
	public static final String CHECK_CONTACT_EXISTS = "SELECT USER_ID FROM USER_DETAIL WHERE CONTACT=?";

	public static final String INSERT_PERSONAL_DETAILS = "INSERT INTO USER_DETAIL(USERNAME, MAIL, CONTACT, ROLE, PASS) VALUES(?,?,?,?,?)";

	public static final String GET_USER_ID = "SELECT USER_ID FROM USER_DETAIL WHERE CONTACT=?";

	public static final String UPDATE_USER_ID = "UPDATE USER_DETAIL SET CREATED_BY=?, UPDATED_BY=?, UPDATED_AT=current_timestamp WHERE CONTACT=?";

	public static final String INSERT_USER_ADDRESS = "INSERT INTO ADDRESS_DETAIL(USER_ID, STREET_ADDRESS, CITY, ZIP_CODE, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?,?)";

	public static final String CHECK_LOGIN = "SELECT ROLE FROM USER_DETAIL WHERE CONTACT=? AND PASS=?";

	public static final String INSERT_CAB_MODEL_DETAILS = "INSERT INTO CAB_MODEL(MODEL_NAME, MODEL_DESCRIPTION, NUMBER_OF_SEATS, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?)";
	
	public static final String GET_MODEL_ID = "SELECT MODEL_ID FROM CAB_MODEL WHERE MODEL_NAME=? AND MODEL_DESCRIPTION=?";

	public static final String INSERT_CAB_LAUNCH_DETAILS = "INSERT INTO CAB_DETAIL(LICENCE_PLATE, MODEL_ID, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?)";

	public static final String GET_MODEL_ID_BY_LICENCE = "SELECT MODEL_ID FROM CAB_DETAIL WHERE LICENCE_PLATE=?";
	
	public static final String UPDATE_CAB_MODEL = "UPDATE CAB_MODEL SET MODEL_NAME=?, MODEL_DESCRIPTION=?, NUMBER_OF_SEATS=?, UPDATED_AT=current_timestamp, UPDATED_BY=? WHERE MODEL_ID=?";

	public static final String DELETE_CAB_MODEL = "DELETE FROM CAB_MODEL WHERE MODEL_ID=?";

	public static final String DELETE_CAB_DETAILS = "DELETE FROM CAB_DETAIL WHERE MODEL_ID=?";

	public static final String DISPLAY_CAB_MODELS = "SELECT LICENCE_PLATE, MODEL_NAME, MODEL_DESCRIPTION, NUMBER_OF_SEATS FROM CAB_DETAIL, CAB_MODEL WHERE CAB_DETAIL.MODEL_ID=CAB_MODEL.MODEL_ID";

	public static final String INSERT_LICENCE_DETAILS = "INSERT INTO DRIVER_DETAIL(USER_ID, LICENCE_NUMBER, ZIP_CODE, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?)";

	public static final String GET_CAB_ID = "SELECT CAB_ID FROM CAB_DETAIL WHERE CAB_STATUS=5";
	
	public static final String INSERT_CAB_DRIVER = "INSERT INTO CAB_DRIVER(DRIVER_ID, CAB_ID, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?)";

	public static final String UPDATE_CAB_STATUS = "UPDATE CAB_DETAIL SET CAB_STATUS=? WHERE CAB_ID=?";
	
	public static final String DISPLAY_LOCATIONS = "SELECT STREET_ADDRESS, ZIP_CODE FROM ADDRESS_DETAIL";

	public static final String GET_ZIP_CODE = "SELECT ZIP_CODE FROM ADDRESS_DETAIL WHERE ADDRESS_ID=?";

	public static final String GET_DRIVER_ID = "SELECT USER_ID FROM DRIVER_DETAIL WHERE DRIVER_STATUS=5 AND ZIP_CODE=?";

	public static final String GET_CAB_DRIVER_ID = "SELECT CAB_ID FROM CAB_DRIVER WHERE DRIVER_ID=?";
	
	public static final String GET_MODEL_BY_CAB_ID = "SELECT MODEL_ID FROM CAB_DETAIL WHERE CAB_ID=?";
	
	public static final String GET_CAB_SEATS = "SELECT NUMBER_OF_SEATS FROM CAB_MODEL WHERE MODEL_ID=?";

	public static final String GET_DRIVER_BY_CAB_ID = "SELECT DRIVER_ID FROM CAB_DRIVER WHERE CAB_ID=?";

	public static final String INSERT_RIDE_DETAILS = "INSERT INTO CAB_RIDE_DETAIL(USER_ID, DRIVER_ID, START_TIME, SOURCE_ADDRESS_ID, DESTINATION_ADDRESS_ID, CAB_ID, PRICE, CREATED_BY, UPDATED_BY) VALUES(?,?,?,?,?,?,?,?,?)";

	public static final String GET_BOOKING_ID = "SELECT CAB_RIDE_ID FROM CAB_RIDE_DETAIL WHERE CUSTOMER_ID=?, DRIVER_ID=?, CAB_ID=?";

	public static final String UPDATE_DRIVER_STATUS = "UPDATE DRIVER_DETAIL SET DRIVER_STATUS=? WHERE USER_ID=?";

}
